routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect('blog');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/about', 'HomeController@viewAboutPage');

//Blog routing
Route::group(['prefix' => 'blog'], function () {

    Route::get('/', 'BlogController@index')->name('blog');

    Route::group(['middleware' => 'auth'], function () {

        Route::get('/create', 'BlogController@createPost')->name('post-create');

        Route::post('/store', 'BlogController@storePost')->name('post-store');

        Route::get('/{post}/edit', 'BlogController@editPost')->name('post-edit');

        Route::post('/{post}/update', 'BlogController@updatePost')->name('post-update');

        Route::get('/{post}/delete', 'BlogController@confirmDeletePost')->name('post-confirm-delete');
        
        Route::delete('/{post}', 'BlogController@deletePost')->name('post-delete');

        Route::post('/{post}/comment', 'BlogController@storeComment')->name('comment-store');

        Route::get('/{post}/post-comment', 'BlogController@redirectToCommentForm')->name('comment-redirect');

    });

    Route::get('/{post}', 'BlogController@viewPost')->name('post-view');
});
//
//Route::get('/search', function (\Illuminate\Http\Request $request) {
//    return \App\Post::search($request->search)->get();
//});

Route::get('/search', 'HomeController@search');

Route::get('/contact-us', 'HomeController@viewContactPage')->name('contact-view');

Route::post('/contact-us', 'HomeController@submitContactForm')->name('contact-submit');

Route::group(['prefix' => 'admin', 'middleware' => ['auth','is_admin']], function () {
    Route::get('/',function (){
       return 'If you get here, you are really a very handsome guy.';
    });
    Route::get('/search/reindex', 'AdminController@searchReindex')->name('search-reindex');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Post extends Model
{
    use Searchable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'summary', 'description'];

    public function user() {
    	return $this->belongsTo('App\User');
    }

    public function getDayPublishedAttribute() {
    	return $this->created_at->format('d-m-Y');
    }

    public function comments() {
        return $this->hasMany('App\Comment');
    }

    /**
     * Get the index name for the model.
     *
     * @return string
     */
    public function searchableAs()
    {
        return 'posts_index';
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $array = $this->toArray();

        // Customize array...

        return $array;
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use App\Repositories\PostRepository;
//use App\Repositories\UserRepository;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;

class BlogController extends Controller
{

    const perPage = 5;

    protected $postRepo;

    public function __construct(PostRepository $postRepository)
    {
        $this->postRepo = $postRepository;
    }

    public function index() {

        $posts = Post::where('publish', true)->orderBy('created_at', 'desc')->simplePaginate($this::perPage);

        return view('blog.index', ['posts' => $posts]);

    }

    public function createPost() {
        return view('blog.create');
    }

    public function storePost(Request $request) {

        $this->validate($request, [
            'title' => 'required|max:255',
            'description' => 'required',
        ]);

        $data = $request->all();

        $post = $this->postRepo->createFromRequest($data);

        return redirect()->route('blog')->with('status', 'Your post is created successfully!');
    }

    public function editPost(Post $post) {

        $this->authorize('update', $post);

        return view('blog.edit', ['post' => $post]);
    }

    public function updatePost(Post $post, Request $request) {

        $this->authorize('update', $post);

        $data = $request->all();

        $post = $this->postRepo->updateFromRequest($post, $data);

        return redirect()->route('blog');
    }

    public function viewPost(Post $post) {

        $comments = $post->comments()->orderBy('created_at', 'desc')->paginate($this::perPage);

        $featured_image = '/images/post-bg.jpg';
        if ($post->featured_image) {
            $featured_image = asset('storage/').'/'.$post->featured_image;
        }

        return view('blog.single', ['post' => $post, 'featured_image' => $featured_image, 'comments' => $comments]);
    }

    public function confirmDeletePost(Post $post) {

        $this->authorize('delete', $post);

        return view('blog.confirm_delete', ['post' => $post]);
    }

    public function deletePost(Post $post) {

        $post->delete();

        return redirect('blog');
    }

    public function storeComment(Request $request, Post $post) {

        $this->validate($request, [
            'comment_body' => 'required'
        ]);

        $comment = new Comment();
        $comment->content = $request->input('comment_body');;
        $comment->post_id = $post->id;
        $comment->user_id = Auth::user()->id;
        $comment->save();
        $redirect_url = route('post-view', $post).'#comment-list';
        return redirect($redirect_url);
    }

    public function redirectToCommentForm(Post $post) {
        $redirect_url = route('post-view', $post).'#comment-form';
        return redirect($redirect_url);
    }
}

resources/views/blog/confirm_delete.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">

                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('post-delete', $post) }}">
                            {{ csrf_field() }}
                            {{ method_field('delete') }}
                            <div class="form-group">
                                <p class="confirmation">Are you sure you want to delete this post?</p>
                                <div class="col-md-12">
                                    <a href="#" onclick="window.history.back()" class="btn btn-default">
                                        Cancel
                                    </a>
                                    <button type="submit" class="btn btn-danger">
                                        Delete
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

            </div>
        </div>
    </div>
@endsection

resources/views/blog/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create a post</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('post-store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-2 control-label">Title</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="title"  id="title" placeholder="Title">
                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="featured_image" class="col-md-2 control-label">Featured image</label>
                                <div class="col-md-10">
                                    <input type="file" id="featured_image" name="featured_image">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="summary" class="col-md-2 control-label">Summary</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" name="summary" id="summary" placeholder="Summary"></textarea>
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="body" class="col-md-2 control-label">Body</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" name="description" id="body" placeholder="Body" rows="5"></textarea>
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="publish" class="col-md-2 control-label">Publish</label>
                                <div class="col-md-8 col-md-offset-1">
                                    <div class="checkbox">
                                        <input type="checkbox" id="publish" name="publish">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-2">
                                    <button type="submit" class="btn btn-primary">
                                        Create
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'body' );
    </script>
    <script src="{{ asset('static') }}/js/vendor/jquery.ui.widget.js"></script>
    <script src="{{ asset('static') }}/js/jquery.iframe-transport.js"></script>
    <script src="{{ asset('static') }}/js/jquery.fileupload.js"></script>
    <script>
        $(function () {
//            $('#fileupload').fileupload({
//                dataType: 'json',
//                done: function (e, data) {
//                    $.each(data.result.files, function (index, file) {
//                        $('<p/>').text(file.name).appendTo(document.body);
//                    });
//                }
//            });
        });
    </script>
@endpush

resources/views/blog/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit &quot;{{ $post->title }}&quot;</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('post-update',[$post]) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="title" class="col-md-2 control-label">Title</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="title"  id="title" placeholder="Title" value="{{ $post->title }}">
                                </div>
                            </div>

                            <div class="form-group field-image">
                                <label for="featured_image" class="col-md-2 control-label">Featured image</label>
                                <div class="col-md-10 field-image-upload">
                                    @if ($post->featured_image)
                                        <img src="{{ asset('storage').'/'.$post->featured_image }}" style="height: 100px; width: auto">
                                        <a href="#" class="delete-image">Delete</a>
                                    @else
                                        <input type="file" id="featured_image" name="featured_image">
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="summary" class="col-md-2 control-label">Summary</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" name="summary" id="summary" placeholder="Summary">{{ $post->summary }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="body" class="col-md-2 control-label">Body</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" name="description" id="body" placeholder="Body" rows="5">{{ $post->description }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="publish" class="col-md-2 control-label">Publish</label>
                                <div class="col-md-8 col-md-offset-1">
                                    <div class="checkbox">
                                        <input type="checkbox" id="publish" name="publish" @if ($post->publish) {{ 'checked' }} @endif>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-2">
                                    <button type="submit" class="btn btn-primary">
                                        Save changes
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'body' );
    </script>
@endpush

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('status'))
            <div class="row">
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            </div>
        @endif
        <div class="row">
            <p>To begin to create a post, click this link <a href="{{ route('post-create') }}" title="Create a post">Create a post</a>.</p>
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                @each('blog.partials.post_index', $posts, 'post', 'blog.partials.post_index_empty')

                {{--Display pagination--}}
                @if (!$posts->isEmpty())
                    {{ $posts->links() }}
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/blog/single.blade.php
@extends('layouts.app')

@section('header-class','post-heading')
@section('header-image', $featured_image)
@section('header-title',$post->title)
@section('header-subtitle',$post->summary)
@section('header-meta')
    <span class="meta">Posted by <a href="#">{{ $post->user->name }}</a> on {{ $post->day_published }}</span>
@endsection

@section('content')
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{--{!! nl2br(e($post->description)) !!}--}}
                    {!! $post->description !!}
                </div>
            </div>
        </div>
    </article>
    <div class="comment-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h3>Post a comment</h3>
                    @if (Auth::check())
                        <form action="{{ route('comment-store', $post) }}" method="post" id="comment-form">

                            {{ csrf_field() }}
                            <div class="form-group{{ $errors->has('comment_body') ? ' has-error' : '' }}">
                                <textarea class="form-control" name="comment_body" placeholder="Post a comment..."></textarea>
                                @if ($errors->has('comment_body'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('comment_body') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Post a comment</button>
                            </div>


                        </form>
                    @else
                        <p>To comment on this post, please <a href="{{ route('comment-redirect', $post) }}" title="login">login</a>.</p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    @include('comments.list', ['comments' => $comments])
                </div>
            </div>
        </div>
    </div>
@endsection